API Changes
- Fixed on newer versions of JAVA, Buffer.flip() changes return value, causing nosuchmethoderror when execution is still valid
- Added methods to calculate time for imagerenderers and a shortcut to get textures directly